name: messageai
description: MessageAI - Cross-platform messaging app with Flutter
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Network & API
  supabase_flutter: ^1.10.0
  dio: ^5.3.0

  # State management
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0

  # Local database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.16

  # Firebase
  firebase_messaging: ^14.6.0

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Code generation
  build_runner: ^2.4.0
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true
