name: messageai
description: MessageAI - Cross-platform messaging app with Flutter
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Network & API
  supabase_flutter: ^1.10.0
  dio: ^5.3.0

  # State management
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0

  # Local database
  drift: ^2.14.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.16

  # Firebase
  firebase_core: 2.32.0
  firebase_messaging: ^14.6.0

  # Local notifications (Phase 06)
  flutter_local_notifications: ^19.0.0

  # UI
  cupertino_icons: ^1.0.2

  # Utilities
  uuid: ^4.0.0
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  path: ^1.8.3
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Code generation
  build_runner: ^2.4.0
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true

dependency_overrides:
  # Completely exclude sign_in_with_apple (uses deprecated Flutter APIs incompatible with latest Android)
  sign_in_with_apple:
  sign_in_with_apple_platform_interface:
  sign_in_with_apple_web:
  js: ^0.7.2
