# Supabase Configuration
# Generated for local development

[project]
project_id = "messageai-local"
account_id = "local"

[api]
enabled = true
port = 54321
protocols = ["http"]
max_body_size = 20

[db]
port = 54322
major_version = 15
shadow_port = 54320

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325

[storage]
file_size_limit = 52428800
s3_host = "localhost"
s3_protocol = "http"
s3_port = 54321

[auth]
enabled = true
email_autoconfirm = true
phone_autoconfirm = true
enable_signup = true

[edge_functions]
enabled = true
port = 54321
