// File generated by FlutterFire CLI.
// This is a placeholder file. To use Firebase, you need to:
// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 2. Run: flutterfire configure
// 3. Follow the prompts to select your Firebase project
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import firebase_options.dart;
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABa-DcxTR4T4CHlfJuy-7DKG1F_hDRNcg',
    appId: '1:397483513751:web:3121cbb846ddd8381c56d2',
    messagingSenderId: '397483513751',
    projectId: 'messageai-e2e9e',
    authDomain: 'messageai-e2e9e.firebaseapp.com',
    storageBucket: 'messageai-e2e9e.firebasestorage.app',
    measurementId: 'G-VCVQDFPTLV',
  );

  // Placeholder values - replace with your actual Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBc-17a_EvWPvCutNSTEV9QEB2w2DUM_4',
    appId: '1:397483513751:android:bb838799a2cd3f7f1c56d2',
    messagingSenderId: '397483513751',
    projectId: 'messageai-e2e9e',
    storageBucket: 'messageai-e2e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIza...',  // Replace with your iOS API key
    appId: '1:...',     // Replace with your iOS app ID
    messagingSenderId: '...',  // Replace with your sender ID
    projectId: 'your-project-id',  // Replace with your project ID
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.messageai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIza...',  // Replace with your macOS API key
    appId: '1:...',     // Replace with your macOS app ID
    messagingSenderId: '...',  // Replace with your sender ID
    projectId: 'your-project-id',  // Replace with your project ID
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.messageai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABa-DcxTR4T4CHlfJuy-7DKG1F_hDRNcg',
    appId: '1:397483513751:web:ba73c764d577f4f51c56d2',
    messagingSenderId: '397483513751',
    projectId: 'messageai-e2e9e',
    authDomain: 'messageai-e2e9e.firebaseapp.com',
    storageBucket: 'messageai-e2e9e.firebasestorage.app',
    measurementId: 'G-C6R3PHYG95',
  );

}
